### ISSUE TITLE
Compiler error on assertThat(Stream) with 3.7.0+

### ISSUE THREAD

**Issue by simonbasle** [joel-costigliola/assertj-core#1046]
#### Summary
I was on AssertJ 3.6.1 and just bumped the dependency to 3.8.0. That caused compiler errors on a few assertions around a `Stream<? extends Scannable>`:

```
error: cannot find symbol
		assertThat(s.inners()).hasSize(1);
		                      ^
  symbol:   method hasSize(int)
  location: class AbstractObjectAssert<CAP#1,Stream<CAP#2>>
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends AbstractObjectAssert<CAP#1,Stream<CAP#2>> from capture of ?
    CAP#2 extends Scannable from capture of ? extends Scannable
```
It reports the same kind of error with `isEmpty()`. Completion in the IDE (IntelliJ) works fine though.
I tested rebuilding with AssertJ 3.7.0 with the same result, but it works fine with 3.6.2.
Any idea about the root cause?

#### Example
```java
default Stream<? extends Scannable> inners() {
	return Stream.empty();
}
```

```java
assertThat(s.inners()).hasSize(1);
```

#### Java 8 specific ?
YES : create Pull Request from the `master` branch

**Comment by joel-costigliola** [comment]
I can't reproduce the issue with AssertJ 3.8.0, this test passes:
```java
@Test
public void stream_with_upper_bound_assertions() {
  // GIVEN
  Stream<? extends TolkienCharacter> hobbits = Stream.of();
  // THEN
  assertThat(hobbits).hasSize(0)
                     .isEmpty();
}
```
Would you be able to give a test case to reproduce the problem ?

**Comment by joel-costigliola** [comment]
The problem comes from the introduction of primitive streams that changed the generic signature of `assertThat(Stream)` to use `BaseStream` instead of `Stream`.
I don't understand exactly why does it fail though.

**Comment by joel-costigliola** [comment]
Fixed with my previous comment solution.
