### ISSUE TITLE
Restore org.assertj.core.api.StrictAssertions

### ISSUE THREAD

**Issue by jrh3k5** [joel-costigliola/assertj-core#499]
It looks like, between versions 3.2.0 and 3.1.0 of `assertj-core`, the `org.assertj.core.api.StrictAssertions` class was removed. This is a little problematic because, I think, Eclipse's import organization is a little bit too smart for my own good. It would see this in my imports:

```java
import static org.assertj.core.api.Assertions.*;
```

...and reduce it to the highest point in the class hierarchy - e.g.:

```java
import static org.assertj.core.api.StrictAssertions.assertThat;
```

This has the unfortunate effect of, when upgrading from 3.1.0 to 3.2.0, causing errors like the following:

```
[ERROR] /home/jrh3k5/src/test/java/com/example/FooTest.java:[7,35] cannot find symbol
  symbol:   class StrictAssertions
  location: package org.assertj.core.api
[ERROR] /home/jrh3k5/src/test/java/com/example/FooTest.java:[7,1] static import only from classes and interfaces
```

Is there a way some kind of transitional class can be instated to allow a smooth transition to whatever class that should be used in its place?

**Comment by joel-costigliola** [comment]
Yep, `StrictAssertions` has been replaced by `AssertionsForClassTypes` see the release notes : http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.2.0.

**Comment by brcolow** [comment]
Just replace:

````java
import static org.assertj.core.api.StrictAssertions.assertThat;
````

with:

````java
import static org.assertj.core.api.Assertions.assertThat;
````

**Comment by jrh3k5** [comment]
The issue with that is that I have about a thousand test classes across a number of projects using assertj-core 3.1.0, which means that I have to go through them and replace and organize imports in each test class to do this. This might be acceptable if this was done in a major version bump (assertj-core 4.0, for example), as it's a non-passive change, but, given that it was a minor version bump, it's a bit of a surprising annoyance to have to make this change just to go from x.1.0 to x.2.0.

**Comment by joel-costigliola** [comment]
Sorry about that ! I have found that introducing `StrictAssertions` was more painful than helpful.
I also had to do the same migration in my current project, a global search and replace was enough.

As for the breaking changes, I don't follow semantic versioning as major version are per JDK (1.x for java 6, 2.x java 7 and 3.x java 8) but I do document breaking changes.

I'm closing this issue as I won't introduce `StrictAssertions` back.
