### ISSUE TITLE
3.2.0 : ThrowableAssert hasNoCause with compilation issue while using raw types

### ISSUE THREAD

**Issue by Eulbobo** [joel-costigliola/assertj-core#522]
Here is a small test class that creates compilation issues while executing it, even if neither IDEA or Eclipse see any problem before execution.

When using a raw typed object, hasNoCause should be called before any other method or it will lead to the following error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project cantdeal: Compilation failure
[ERROR] /.../src/test/java/cantdeal/ThrowableAssert_hasNoCause_Test.java:[79,17] cannot find symbol
[ERROR] symbol:   method hasNoCause()
[ERROR] location: class org.assertj.core.api.AbstractAssert

No error while using a fully typed object

[ThrowableAssert_hasNoCause_Test.txt](https://github.com/joel-costigliola/assertj-core/files/33942/ThrowableAssert_hasNoCause_Test.txt)

**Comment by joel-costigliola** [comment]
I was able to reproduce it from maven, it runs fine in eclipse though.
Investigation needed.

**Comment by joel-costigliola** [comment]
I 'm still puzzled by this issue, I have found that if you extract the lambda to a variable the compilation error disappears, the following code works compiles and run properly in maven :
```java
ThrowingCallable code = () -> MyInterface.fromCode(1, MyRawObject.class);
assertThatThrownBy(code).as("without a cause")
                         .hasNoCause()
                         .as("Exception thrown by method is a null pointer Exception")
                         .isInstanceOf(NullPointerException.class);
```
For information purpose, I'm showing the non compiling code: 

```java
assertThatThrownBy(() -> MyInterface.fromCode(1, MyRawObject.class))
                  .as("without a cause")
                  .hasNoCause()
                  .as("Exception thrown by method is a null pointer Exception")
                  .isInstanceOf(NullPointerException.class);
```

**Comment by PascalSchumacher** [comment]
Maybe it is a JDK bug. The compile error still occurs with jdk1.8.0_112.

**Comment by PascalSchumacher** [comment]
Does not work with jdk 1.8.0_152, but works with jdk 9.0.1, so it realy is a compiler bug.
