### ISSUE TITLE
No isEqualToComparingFieldByField for Comparable's anymore in version 1.7.0

### ISSUE THREAD

**Issue by lestard** [joel-costigliola/assertj-core#322]
Today I tried to update the assertj version in my project from 1.6.1 to 1.7.0 but I got compilation errors in some tests because the method `isEqualToComparingFieldByField` can't be found anymore. 

My class looks like this: 
```java
public class MyClass implements Comparable<MyClass> {
 ...
}
```
In the test I was writing something like this:
```java
MyClass first = ...
MyClass second = ...

assertThat(first).isEqualToComparingFieldByField(second);
```

This worked in version 1.6.1 but breaks in 1.7.0. 

I think the reason for this is issue #207. Before this change when calling `assertThat` the variant with the signature `<T> ObjectAssert<T> assertThat(T actual)` was used. After the change now `<T extends Comparable<T>> GenericComparableAssert<T> assertThat(T actual)` is used instead which has no `isEqualToComparingFieldByField` method.

Am I missing something? Can this be fixed or is there a workaround to still use the assertion for Comparable's? Maybe this breaking change can be mentioned in the changelog.

Thanks for support and thanks for the great library!

**Comment by joel-costigliola** [comment]
This is a regression indeed, thanks for reporting it, `AbstractComparableAssert` should have inherited from `ObjectAssert` to provide `isEqualToComparingFieldByField`.

To use `isEqualToComparingFieldByField` you can simply cast your object under test to `Object` so that `assertThat((Object) first)` returns an `ObjectAssert` but then you won't have access to comparable assertions.

```java
// Object assert
assertThat((Object)first).isEqualToComparingFieldByField(second);
// Comparable assert
assertThat(first).isLessThan(second);
```

**Comment by joel-costigliola** [comment]
This is documented now : http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-1.7.0

**Comment by joel-costigliola** [comment]
@lestard  I have set the fix to 2.0 but if you feel you need it right away, I can cut a 1.7.2 release.
You tell me.

**Comment by lestard** [comment]
@joel-costigliola 2.0 is fine. Thanks for the fix.
