### ISSUE TITLE
Use opentest4j as a transitive dependency

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#1070]
#### Summary
By the initiative of the JUnit 5 team the [opentest4j](https://github.com/ota4j-team/opentest4j) project has been created. JUnit 5 uses it for reporting errors, assumptions and multiple errors. In their README it says that they have reached out to assertj, but I couldn't find an issue linked to it.

My proposal is to pull in opentest4j as a transitive dependency and drop the dependencies to JUnit. I think that all IDEs that have support for JUnit 5 have support for opentest4j because JUnit 5 is using that.

This would make a lot of things easier in AssertJ as we won't need to check for JUnit and would definitely improve the support for assumptions and also for users using something else apart from JUnit.

I would like to hear your opinion about this.

#### Java 8 specific ?
* NO  : create Pull Request from the `2.x` branch

From what I could see opentest4j has a target of Java 6 version.

**Comment by filiphr** [comment]
An alternative would be to have an optional support for opentest4j (like there is for JUnit 4), and preference opentest4j if it is there.

**Comment by joel-costigliola** [comment]
We are using JUnit to report some error nicely displayed in IDEs, if we stop doing that I believe people using old IDEs version won't benefit from it, am I right? 

Having said that, I'm sympathetic to be JUnit agnostic.

I'm not sure to understand the point about assumptions, there is no assumptions code in opentest4j.

**Comment by filiphr** [comment]
You are right old IDEs will stop working, but I would say if someone has opentest4j on the classpath we should use those instead of the JUnit ones. If they have it they most probably use JUnit 5 and JUnit 5 uses it for their own errors.

Therefore my second comment, maybe it would be best if we support opentest4j if it is there.

opentest4j has [`TestAbortedException`](https://github.com/ota4j-team/opentest4j/blob/master/src/main/java/org/opentest4j/TestAbortedException.java) which is used for failed assumptions. That is what JUnit 5 uses for the assumptions.

**Comment by joel-costigliola** [comment]
I guess what we could do as a first step is start returning `org.opentest4j.AssertionFailedError` if `org.junit.ComparisonFailure` (JUnit 4) is not available, if both are not available we just return a simple `AssertionError` as usual.

**Comment by JaimieW** [comment]
Not sure if this is the relevant place for this, but after updating to v3.12 my project started getting NoClassDefFoundErrors on org.opentest4j.MultipleFailuresError:

`java.lang.NoClassDefFoundError: org/opentest4j/MultipleFailuresError
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.assertj.core.internal.Failures.<init>(Failures.java:46)
        at org.assertj.core.internal.Failures.<clinit>(Failures.java:44)
        at org.assertj.core.internal.Objects.<init>(Objects.java:87)
        at org.assertj.core.internal.Objects.<init>(Objects.java:101)
        at org.assertj.core.internal.Objects.<clinit>(Objects.java:82)
        at org.assertj.core.api.AbstractAssert.<init>(AbstractAssert.java:65)
        at org.assertj.core.api.AbstractObjectAssert.<init>(AbstractObjectAssert.java:60)
        at org.assertj.core.api.AbstractComparableAssert.<init>(AbstractComparableAssert.java:40)
        at org.assertj.core.api.GenericComparableAssert.<init>(GenericComparableAssert.java:23)
        at org.assertj.core.api.AssertionsForInterfaceTypes.assertThat(AssertionsForInterfaceTypes.java:325)
        at org.assertj.core.api.Assertions.assertThat(Assertions.java:2796)
        at com.simulity.smdp.async.procedure.common.SendDataVerticleTest.lambda$shouldSendReplyOnUnexpectedExceptionOnSendData$2(SendDataVerticleTest.java:123)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:223)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:200)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:533)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.ClassNotFoundException: org.opentest4j.MultipleFailuresError
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 34 more`

If opentest is now an upstream dependency of assertj, then I'd vote that it is added as a transitive dependency.

**Comment by sbrannen** [comment]
> Not sure if this is the relevant place for this, but after updating to v3.12

Do you mean 3.12 or 3.13?

If you meant the latter, then upgrading 3.13.1 should fix the problem.

**Comment by JaimieW** [comment]
It was 3.12, but I'll try 3.13.1, thanks.

**Comment by joel-costigliola** [comment]
@JaimieW let us know if 3.13.1 fixes your issue (it should)

**Comment by JaimieW** [comment]
@joel-costigliola I just tried 3.13.1 and everything seems to be good.  Thanks for the help.
